### ISSUE TITLE
Internal visibility

### ISSUE THREAD

**Issue by dzikoysk** [coditory/gradle-integration-test-plugin#13]
Integration set of sources is resolved as standalone module in IntelliJ, so test sources in Kotlin cannot relay on `internal` visibility from the main module:

![image](https://user-images.githubusercontent.com/4235722/139710771-81a85bf3-3d6e-4daa-a452-82e4d4120e08.png)
 
In theory it's not that bad as it forces us to expose only things we want to share and test only these parts of our api, but in real world it kinda hurts, because we cannot use some e.g. utilities dedicated for internal usage.

**Comment by pmendelski** [comment]
Hi, sorry for the delay :)
I agree with you, it's a bit cleaner but impractical. Today I faced the same problem in my project. Moreover, I would like integration tests to be configured as similar to unit tests as possible ...and unit tests can access internal scoped objects from the main.

If you're still interested, I've added support for kotlin internal scope to integration tests in version `1.4.2`.

**Comment by dzikoysk** [comment]
Oh, nice! ❤️ I'm using the plugin for [Reposilite](https://github.com/dzikoysk/reposilite) where we have some runners/utility extension functions with internal scope to simplify setup and test scenarios. Now can use them without a need to make them public :)

**Comment by wartoshika** [comment]
I would like to reopen this issue because this exact problem still occurs to me.

![image](https://user-images.githubusercontent.com/16635648/179476945-6cc2d0b1-f047-479f-967d-e0ecb6d68a75.png)

I have done the following Steps to get the problem:

- Downloading a copy of your [plugin-sample](https://github.com/coditory/gradle-integration-test-plugin-sample) repository (latest commit sha was 509212a)
- Loading this project into Intellij IDEA Ultimate 2022.1.3 (Build #IU-221.5921.22, built on June 21, 2022)
- Let Gradle download dependencies and update indices
- Open file `kotlin-junit5/src/integration/com/coditory/sandbox/SimpleIntegrationSpec.kt`
- Seeing internal access with error message `Cannot access 'InternalObject': it is internal in ''`

Running the `integrationTest` task on gradle does work (I think that this is possible due to the fact that kotlin internal classes will be publicly accessable after byte code transformation)

I have verified that this sample project uses the version `1.4.2`.

Help is appreciated, thanks

**Comment by pmendelski** [comment]
@wartoshika thanks for the detailed description.

I reproduced the problem and discovered that when I remove the `.idea` folder and reimport the project the error disappears. I don't know why yet. I'll take a look into it in a spare moment.

**Comment by wartoshika** [comment]
Thanks for the quick response. Your discovery may be a good hint. Ill also try to dig into this problem and try to support.

**Comment by pmendelski** [comment]
@dzikoysk @wartoshika fix is available in `v1.4.4`

@wartoshika thanks for your analysis and contribution 🎉
