### ISSUE TITLE
IdeaPlugin Disable question

### ISSUE THREAD

**Issue by vbaidak** [coditory/gradle-integration-test-plugin#26]
Hi Team!

I noticed you removed `IdeaPlugin` configuration (marking test sources and resources) in this commit:
`b67f75ac55cc71d7ca51f372bc2f3e991d922dcd` (Removed IdeaPlugin sources directory assignment for integration tests… )

Could you please clarify, why?

**Comment by pmendelski** [comment]
Hi, thanks for asking.

The Idea plugin was [disabled](https://github.com/coditory/gradle-integration-test-plugin/pull/16) to make internally visible Kotlin classes available in integration tests.

There is an issue reported on [YouTrack](https://youtrack.jetbrains.com/issue/KTIJ-7662/IDE-support-internal-visibility-introduced-by-associated-compilations#focus=Comments-27-6474878.0-0) around this problem.  ATM, we must pick either internal visibility or properly marked test directories in Idea. I picked the first option, but I will gladly add idea support when the issue is solved.
